Updated ncchinfo_gen.py to include correct Syntax
the print statements didn't have parentheses.
This fixes the errors:
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(*code*)?
SyntaxError: invalid syntax